// <auto-generated />
using APIWeb.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace APIWeb.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20221215150346_initializeDb")]
    partial class initializeDb
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("APIWeb.Entities.Arms", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    b.Property<string>("EnemysNameArms")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("HeroesNameArms")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<long>("bonusForce")
                        .HasColumnType("bigint");

                    b.Property<long>("bonusSagesse")
                        .HasColumnType("bigint");

                    b.Property<long>("bonusVitality")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.ToTable("Arms");
                });

            modelBuilder.Entity("APIWeb.Entities.Enemys", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    b.Property<string>("EnemysArms")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("classePlayer")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<long>("force")
                        .HasColumnType("bigint");

                    b.Property<string>("name")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<long>("sagesse")
                        .HasColumnType("bigint");

                    b.Property<long>("vitality")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.ToTable("Enemys");
                });

            modelBuilder.Entity("APIWeb.Entities.Hero", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    b.Property<string>("HeroesArms")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("classePlayer")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<long>("force")
                        .HasColumnType("bigint");

                    b.Property<string>("name")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<long>("sagesse")
                        .HasColumnType("bigint");

                    b.Property<long>("vitality")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.ToTable("Heroes");
                });
#pragma warning restore 612, 618
        }
    }
}
